spring:
  application:
    name: bankatmsystem

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/bank_atm_system
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
